PYTEST ?= $(shell command -v $(CURDIR)/app/env/bin/pytest 2>/dev/null || command -v pytest)

.PHONY: help env install lock build build-bot up down restart rebuild clean clean-logs test

help: ## Show this help
	@awk 'BEGIN {FS = ":.*##"; printf "Usage: make \033[36m<target>\033[0m\n\nTargets:\n"} \
		/^[a-zA-Z_-]+:.*?##/ { printf "  \033[36m%-12s\033[0m %s\n", $$1, $$2 }' $(MAKEFILE_LIST)

# ── Setup ──────────────────────────────────────────────────────────────────────

env: ## Copy .env.template to .env (skips if .env already exists)
	@test -f .env && echo ".env already exists, skipping" || (cp .env.template .env && echo "Created .env from template")

install: ## Install Python dependencies via Poetry
	cd app && poetry install

lock: ## Re-solve and update poetry.lock
	cd app && poetry lock

test: ## Run the pytest suite (override with PYTEST=... if needed)
	cd app && $(PYTEST) tests/ -v

# ── Docker ─────────────────────────────────────────────────────────────────────

build: ## Build all Docker images
	docker compose build

build-bot: ## Build only the bot image
	docker compose build bot

up: ## Start all services in the background
	docker compose up -d

down: ## Stop and remove containers
	docker compose down

restart: ## Restart running services
	docker compose restart

rebuild: ## Tear down, rebuild images, and start all services
	$(MAKE) down
	$(MAKE) build
	$(MAKE) up

# ── Cleanup ────────────────────────────────────────────────────────────────────

clean: ## Remove containers and all built images
	docker compose down --rmi all

clean-logs: ## Delete worker log files generated by init-app.sh
	rm -f app/*.log
